package grpcserver_test

import (
	"context"
	"fmt"
	"net"
	"slices"
	"sort"
	"sync"
	"testing"
	"time"

	"github.com/rs/zerolog"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/test/bufconn"

	provisioningv1 "github.com/sukko-dev/sukko/gen/proto/sukko/provisioning/v1"
	"github.com/sukko-dev/sukko/internal/provisioning"
	"github.com/sukko-dev/sukko/internal/provisioning/eventbus"
	"github.com/sukko-dev/sukko/internal/provisioning/grpcserver"
	"github.com/sukko-dev/sukko/internal/provisioning/revocation"
	"github.com/sukko-dev/sukko/internal/provisioning/testutil"
	"github.com/sukko-dev/sukko/internal/shared/logging"
	"github.com/sukko-dev/sukko/internal/shared/types"
)

const bufSize = 1024 * 1024

// testPublicKeyPEM is a valid EC P-256 public key for tests.
const testPublicKeyPEM = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEVs/o5+uQbTjL3chynL4wXgUg2R9
q9UU8I5mEovUf86QZ7kOBIjJwqnzD1omageEHWwHdBO6B+dFabmdT9POxg==
-----END PUBLIC KEY-----`

// mockChannelRulesStore is a minimal in-memory ChannelRulesStore for gRPC server tests.
type mockChannelRulesStore struct {
	mu    sync.RWMutex
	rules map[string]*types.TenantChannelRules
}

func newMockChannelRulesStore() *mockChannelRulesStore {
	return &mockChannelRulesStore{rules: make(map[string]*types.TenantChannelRules)}
}

func (m *mockChannelRulesStore) Create(_ context.Context, tenantID string, rules *types.ChannelRules) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.rules[tenantID] = &types.TenantChannelRules{
		TenantID: tenantID,
		Rules:    *rules,
	}
	return nil
}

func (m *mockChannelRulesStore) Get(_ context.Context, tenantID string) (*types.TenantChannelRules, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if r, ok := m.rules[tenantID]; ok {
		return r, nil
	}
	return nil, types.ErrChannelRulesNotFound
}

func (m *mockChannelRulesStore) GetRules(_ context.Context, tenantID string) (*types.ChannelRules, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if r, ok := m.rules[tenantID]; ok {
		return &r.Rules, nil
	}
	return nil, types.ErrChannelRulesNotFound
}

func (m *mockChannelRulesStore) Update(_ context.Context, tenantID string, rules *types.ChannelRules) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.rules[tenantID] = &types.TenantChannelRules{
		TenantID: tenantID,
		Rules:    *rules,
	}
	return nil
}

func (m *mockChannelRulesStore) Delete(_ context.Context, tenantID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.rules, tenantID)
	return nil
}

func (m *mockChannelRulesStore) List(_ context.Context) ([]*types.TenantChannelRules, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	result := make([]*types.TenantChannelRules, 0, len(m.rules))
	for _, r := range m.rules {
		result = append(result, r)
	}
	return result, nil
}

// testEnv holds all test infrastructure.
type testEnv struct {
	bus      *eventbus.Bus
	client   provisioningv1.ProvisioningInternalServiceClient
	cancel   context.CancelFunc
	conn     *grpc.ClientConn
	revStore *revocation.Store
}

// newTestService builds a seeded mock-store-backed provisioning.Service + event bus.
// Extracted so the required-field rejection test (TestNewServer_NilRevocationStore) can obtain
// a valid svc/bus without the full bufconn env (§X — no duplicated construction).
func newTestService(t *testing.T, extraSeed ...func(ctx context.Context, tenantStore *testutil.MockTenantStore)) (*provisioning.Service, *eventbus.Bus) {
	t.Helper()
	logger := zerolog.Nop()

	tenantStore := testutil.NewMockTenantStore()
	keyStore := testutil.NewMockKeyStore()
	routingRulesStore := testutil.NewMockRoutingRulesStore()
	quotaStore := testutil.NewMockQuotaStore()
	auditStore := testutil.NewMockAuditStore()
	channelRulesStore := newMockChannelRulesStore()

	ctx := context.Background()

	// Seed tenant (tenant.ID is a UUID generated by NewTestTenant; tenant.Slug is "test-tenant").
	tenant := testutil.NewTestTenant("test-tenant")
	if err := tenantStore.Create(ctx, tenant); err != nil {
		t.Fatalf("seed tenant: %v", err)
	}

	// Seed key — TenantID is the UUID (stored as FK in key records).
	key := testutil.NewTestTenantKey("key-one", tenant.ID)
	key.Algorithm = "ES256"
	key.PublicKey = testPublicKeyPEM
	if err := keyStore.Create(ctx, key); err != nil {
		t.Fatalf("seed key: %v", err)
	}

	// Seed routing rules keyed by UUID (service lookups use tenant.ID).
	routingRulesStore.Seed(tenant.ID, []provisioning.TopicRoutingRule{
		{Pattern: "**.trade", Topics: []string{"trade"}, Priority: 1},
	})

	// Seed channel rules keyed by UUID (service lookups use tenant.ID).
	if err := channelRulesStore.Create(ctx, tenant.ID, &types.ChannelRules{
		Public:  []string{"*.trade"},
		Default: []string{"news"},
	}); err != nil {
		t.Fatalf("seed channel rules: %v", err)
	}

	for _, seed := range extraSeed {
		seed(ctx, tenantStore)
	}

	bus := eventbus.New(logger)
	svc, svcErr := provisioning.NewService(provisioning.ServiceConfig{
		TenantStore:       tenantStore,
		KeyStore:          keyStore,
		APIKeyStore:       testutil.NewMockAPIKeyStore(),
		RoutingRulesStore: routingRulesStore,
		QuotaStore:        quotaStore,
		AuditStore:        auditStore,
		ChannelRulesStore: channelRulesStore,
		KafkaAdmin:        testutil.NewMockKafkaAdmin(),
		EventBus:          bus,
		Logger:            logger,
		TopicNamespace:    "test",
	})
	if svcErr != nil {
		t.Fatalf("NewService: %v", svcErr)
	}
	return svc, bus
}

// setupTestEnv creates a gRPC server with mock-store-backed service on bufconn.
func setupTestEnv(t *testing.T, extraSeed ...func(ctx context.Context, tenantStore *testutil.MockTenantStore)) *testEnv {
	t.Helper()

	logger := zerolog.Nop()
	svc, bus := newTestService(t, extraSeed...)

	revStore := revocation.New(logger)
	srv, srvErr := grpcserver.NewServer(svc, bus, logger, grpcserver.ServerConfig{
		MaxTenantsFetchLimit: 10000,
		RevocationStore:      revStore, // required by NewServer; always constructed in production
	})
	if srvErr != nil {
		revStore.Close()
		t.Fatalf("NewServer: %v", srvErr)
	}

	// Create bufconn listener
	lis := bufconn.Listen(bufSize)

	gs := grpc.NewServer()
	provisioningv1.RegisterProvisioningInternalServiceServer(gs, srv)

	var wg sync.WaitGroup
	wg.Go(func() {
		defer logging.RecoverPanic(zerolog.Nop(), "grpc_test_server", nil)
		_ = gs.Serve(lis) // Error non-actionable: server stopped by t.Cleanup
	})

	_, cancel := context.WithCancel(context.Background())

	conn, err := grpc.NewClient("passthrough:///bufconn",
		grpc.WithContextDialer(func(_ context.Context, _ string) (net.Conn, error) {
			return lis.Dial()
		}),
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		cancel()
		t.Fatalf("dial bufconn: %v", err)
	}

	client := provisioningv1.NewProvisioningInternalServiceClient(conn)

	t.Cleanup(func() {
		cancel()
		_ = conn.Close()
		gs.Stop()
		wg.Wait()
		revStore.Close()
	})

	return &testEnv{
		bus:      bus,
		client:   client,
		cancel:   cancel,
		conn:     conn,
		revStore: revStore,
	}
}

func TestWatchKeys_Snapshot(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	stream, err := env.client.WatchKeys(ctx, &provisioningv1.WatchKeysRequest{})
	if err != nil {
		t.Fatalf("WatchKeys() error = %v", err)
	}

	resp, err := stream.Recv()
	if err != nil {
		t.Fatalf("Recv() error = %v", err)
	}

	if !resp.GetIsSnapshot() {
		t.Error("first message should be a snapshot")
	}

	if len(resp.GetKeys()) != 1 {
		t.Fatalf("expected 1 key in snapshot, got %d", len(resp.GetKeys()))
	}

	key := resp.GetKeys()[0]
	if key.GetKeyId() != "key-one" {
		t.Errorf("key ID = %q, want %q", key.GetKeyId(), "key-one")
	}
	// TenantId is the tenant UUID (TenantKey.TenantID is a UUID FK after slug/UUID separation).
	if len(key.GetTenantUuid()) != 36 {
		t.Errorf("key tenant ID = %q, expected UUID (len 36)", key.GetTenantUuid())
	}
	if key.GetAlgorithm() != "ES256" {
		t.Errorf("key algorithm = %q, want %q", key.GetAlgorithm(), "ES256")
	}
}

func TestWatchKeys_Delta(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	stream, err := env.client.WatchKeys(ctx, &provisioningv1.WatchKeysRequest{})
	if err != nil {
		t.Fatalf("WatchKeys() error = %v", err)
	}

	// Receive snapshot
	_, err = stream.Recv()
	if err != nil {
		t.Fatalf("Recv snapshot error = %v", err)
	}

	// Publish KeysChanged event
	env.bus.Publish(eventbus.Event{Type: eventbus.KeysChanged})

	// Receive delta
	resp, err := stream.Recv()
	if err != nil {
		t.Fatalf("Recv delta error = %v", err)
	}

	if resp.GetIsSnapshot() {
		t.Error("second message should be a delta, not snapshot")
	}

	if len(resp.GetKeys()) != 1 {
		t.Errorf("expected 1 key in delta, got %d", len(resp.GetKeys()))
	}
}

func TestWatchTenantConfig_Snapshot(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	stream, err := env.client.WatchTenantConfig(ctx, &provisioningv1.WatchTenantConfigRequest{})
	if err != nil {
		t.Fatalf("WatchTenantConfig() error = %v", err)
	}

	resp, err := stream.Recv()
	if err != nil {
		t.Fatalf("Recv() error = %v", err)
	}

	if !resp.GetIsSnapshot() {
		t.Error("first message should be a snapshot")
	}

	if len(resp.GetTenants()) != 1 {
		t.Fatalf("expected 1 tenant config in snapshot, got %d", len(resp.GetTenants()))
	}

	tc := resp.GetTenants()[0]
	if tc.GetTenantSlug() != "test-tenant" {
		t.Errorf("tenant ID = %q, want %q", tc.GetTenantSlug(), "test-tenant")
	}
	// tenant_uuid MUST be populated so the gateway can resolve slug->UUID for the
	// JWT tenant binding. previous_slug is empty here (no rename in this fixture).
	if tc.GetTenantUuid() == "" {
		t.Error("tenant_uuid should be populated in the snapshot")
	}
	if tc.GetPreviousSlug() != "" {
		t.Errorf("previous_slug = %q, want empty (no rename)", tc.GetPreviousSlug())
	}

	if tc.GetChannelRules() == nil {
		t.Fatal("expected channel rules, got nil")
	}
	if len(tc.GetChannelRules().GetPublicChannels()) != 1 || tc.GetChannelRules().GetPublicChannels()[0] != "*.trade" {
		t.Errorf("public channels = %v, want [*.trade]", tc.GetChannelRules().GetPublicChannels())
	}

	// Verify routing rules are included in the snapshot
	if len(tc.GetRoutingRules()) != 1 {
		t.Fatalf("expected 1 routing rule in snapshot, got %d", len(tc.GetRoutingRules()))
	}
	if tc.GetRoutingRules()[0].GetPattern() != "**.trade" {
		t.Errorf("routing rule pattern = %q, want %q", tc.GetRoutingRules()[0].GetPattern(), "**.trade")
	}
	if tc.GetRoutingRules()[0].GetTopicSuffix() != "trade" {
		t.Errorf("routing rule topic_suffix (compat) = %q, want %q", tc.GetRoutingRules()[0].GetTopicSuffix(), "trade")
	}
	if len(tc.GetRoutingRules()[0].GetTopics()) != 1 || tc.GetRoutingRules()[0].GetTopics()[0] != "trade" {
		t.Errorf("routing rule topics = %v, want [trade]", tc.GetRoutingRules()[0].GetTopics())
	}
}

func TestWatchTopics_Snapshot(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	stream, err := env.client.WatchTopics(ctx, &provisioningv1.WatchTopicsRequest{
		Namespace: "test",
	})
	if err != nil {
		t.Fatalf("WatchTopics() error = %v", err)
	}

	resp, err := stream.Recv()
	if err != nil {
		t.Fatalf("Recv() error = %v", err)
	}

	if !resp.GetIsSnapshot() {
		t.Error("first message should be a snapshot")
	}

	// ADR-0006: the consume set = the tenant's deterministic default topic ∪ the
	// suffixes its routing rules reference. Default consumer type is shared.
	got := append([]string(nil), resp.GetSharedTopics()...)
	sort.Strings(got)
	want := []string{"test.test-tenant.default", "test.test-tenant.trade"}
	if !slices.Equal(got, want) {
		t.Errorf("shared topics = %v, want %v", got, want)
	}
}

// TestWatchTopics_RulelessTenantContributesDefaultTopic pins the ADR-0006 fix that
// makes Community ingest possible: a tenant with NO routing rules (rules are
// Pro-gated) must still contribute its default topic to the consume/create set —
// previously such tenants were skipped entirely, so their topics were never
// physically created nor consumed and free-tier ingest was structurally dead.
func TestWatchTopics_RulelessTenantContributesDefaultTopic(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t, func(ctx context.Context, tenantStore *testutil.MockTenantStore) {
		ruleless := testutil.NewTestTenant("community-tenant")
		if err := tenantStore.Create(ctx, ruleless); err != nil {
			t.Fatalf("seed ruleless tenant: %v", err)
		}
	})

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	stream, err := env.client.WatchTopics(ctx, &provisioningv1.WatchTopicsRequest{Namespace: "test"})
	if err != nil {
		t.Fatalf("WatchTopics() error = %v", err)
	}
	resp, err := stream.Recv()
	if err != nil {
		t.Fatalf("Recv() error = %v", err)
	}

	got := append([]string(nil), resp.GetSharedTopics()...)
	sort.Strings(got)
	want := []string{"test.community-tenant.default", "test.test-tenant.default", "test.test-tenant.trade"}
	if !slices.Equal(got, want) {
		t.Errorf("shared topics = %v, want %v (the ruleless tenant's default topic must be present, and only that)", got, want)
	}
}

func TestStream_ContextCancellation(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)

	stream, err := env.client.WatchKeys(ctx, &provisioningv1.WatchKeysRequest{})
	if err != nil {
		cancel()
		t.Fatalf("WatchKeys() error = %v", err)
	}

	// Receive snapshot
	_, err = stream.Recv()
	if err != nil {
		cancel()
		t.Fatalf("Recv snapshot error = %v", err)
	}

	// Cancel context
	cancel()

	// Next Recv should return error
	_, err = stream.Recv()
	if err == nil {
		t.Error("expected error after context cancellation")
	}
}

func TestWatchAPIKeys_Snapshot(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	stream, err := env.client.WatchAPIKeys(ctx, &provisioningv1.WatchAPIKeysRequest{})
	if err != nil {
		t.Fatalf("WatchAPIKeys() error = %v", err)
	}

	resp, err := stream.Recv()
	if err != nil {
		t.Fatalf("Recv() error = %v", err)
	}

	if !resp.GetIsSnapshot() {
		t.Error("first message should be a snapshot")
	}

	// No API keys are seeded in setupTestEnv, so snapshot should be empty.
	if len(resp.GetApiKeys()) != 0 {
		t.Errorf("expected 0 api keys in snapshot, got %d", len(resp.GetApiKeys()))
	}

	if len(resp.GetRemovedKeyIds()) != 0 {
		t.Errorf("expected 0 removed key IDs in snapshot, got %d", len(resp.GetRemovedKeyIds()))
	}
}

func TestWatchAPIKeys_Delta(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	stream, err := env.client.WatchAPIKeys(ctx, &provisioningv1.WatchAPIKeysRequest{})
	if err != nil {
		t.Fatalf("WatchAPIKeys() error = %v", err)
	}

	// Receive snapshot
	_, err = stream.Recv()
	if err != nil {
		t.Fatalf("Recv snapshot error = %v", err)
	}

	// Publish APIKeysChanged event
	env.bus.Publish(eventbus.Event{Type: eventbus.APIKeysChanged})

	// Receive delta
	resp, err := stream.Recv()
	if err != nil {
		t.Fatalf("Recv delta error = %v", err)
	}

	if resp.GetIsSnapshot() {
		t.Error("second message should be a delta, not snapshot")
	}

	// No API keys seeded, so delta should also have 0 keys.
	if len(resp.GetApiKeys()) != 0 {
		t.Errorf("expected 0 api keys in delta, got %d", len(resp.GetApiKeys()))
	}
}

// TestNewServer_NilRevocationStore asserts NewServer rejects a nil RevocationStore. revStore is
// always constructed in production (main.go), so a nil store is a wiring bug, not a valid
// optional-absence — the required-field guard turns a re-omission into a startup error rather than
// a silent Unimplemented. Structural regression guard: fails against an optional-store build.
func TestNewServer_NilRevocationStore(t *testing.T) {
	t.Parallel()
	svc, bus := newTestService(t)
	_, err := grpcserver.NewServer(svc, bus, zerolog.Nop(), grpcserver.ServerConfig{
		MaxTenantsFetchLimit: 10000,
		RevocationStore:      nil,
	})
	if err == nil {
		t.Fatal("expected error for nil RevocationStore (required dependency)")
	}
}

// TestWatchTokenRevocations_SnapshotAndDelta pins the snapshot-as-delta contract: the initial
// message is a snapshot and every TokenRevocationsChanged delta carries the FULL current set. It
// drives N concurrent revStore writers during an active stream so the store-writer / Snapshot()-reader
// race is exercised under -race.
func TestWatchTokenRevocations_SnapshotAndDelta(t *testing.T) { //nolint:paralleltest // uses shared gRPC test server
	env := setupTestEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	stream, err := env.client.WatchTokenRevocations(ctx, &provisioningv1.WatchTokenRevocationsRequest{})
	if err != nil {
		t.Fatalf("WatchTokenRevocations: %v", err)
	}

	// First message MUST be a snapshot (empty — no revocations yet).
	snap, err := stream.Recv()
	if err != nil {
		t.Fatalf("recv snapshot: %v", err)
	}
	if !snap.GetIsSnapshot() {
		t.Errorf("first message IsSnapshot = false, want true (snapshot-on-connect)")
	}

	future := time.Now().Add(time.Hour).Unix()
	const n = 8
	var wg sync.WaitGroup
	for i := range n {
		jti := fmt.Sprintf("revoke-jti-%d", i)
		wg.Go(func() {
			defer logging.RecoverPanic(zerolog.Nop(), "revoke-writer", nil)
			if rErr := env.revStore.Revoke(revocation.Entry{
				TenantID:  "t1",
				Type:      "token",
				JTI:       jti,
				RevokedAt: time.Now().Unix(),
				ExpiresAt: future,
			}); rErr != nil {
				t.Errorf("revoke %s: %v", jti, rErr)
			}
			env.bus.Publish(eventbus.Event{Type: eventbus.TokenRevocationsChanged})
		})
	}
	wg.Wait()

	// Each delta is a FULL snapshot; drain until all N jtis are observed (snapshot-as-delta contract).
	deadline := time.Now().Add(5 * time.Second)
	seen := map[string]bool{}
	for len(seen) < n && time.Now().Before(deadline) {
		delta, rErr := stream.Recv()
		if rErr != nil {
			t.Fatalf("recv delta: %v", rErr)
		}
		if delta.GetIsSnapshot() {
			t.Errorf("delta IsSnapshot = true, want false")
		}
		for _, r := range delta.GetRevocations() {
			if r.GetJti() != "" {
				seen[r.GetJti()] = true
			}
		}
	}
	if len(seen) != n {
		t.Errorf("observed %d/%d revocations across deltas — snapshot-as-delta must carry the full set", len(seen), n)
	}
}
