{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ws-gateway.fullname" . }}
  labels:
    {{- include "ws-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "ws-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
