{{- if and .Values.enabled .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-loki
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: loki
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/loki-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: loki
    spec:
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          ports:
            - name: http
              containerPort: {{ .Values.loki.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.loki.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: {{ include "monitoring.fullname" . }}-loki-config
        - name: data
          emptyDir: {}
{{- end }}
