{{- if and .Values.enabled .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-loki-config
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: {{ .Values.loki.port }}

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    limits_config:
      retention_period: {{ .Values.loki.retention }}

    compactor:
      working_directory: /loki/compactor
      shared_store: filesystem
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
{{- end }}
