{{- if and .Values.enabled .Values.promtail.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "monitoring.fullname" . }}-promtail
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
spec:
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: promtail
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/promtail-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: promtail
    spec:
      serviceAccountName: {{ include "monitoring.fullname" . }}-promtail
      containers:
        - name: promtail
          image: "{{ .Values.promtail.image.repository }}:{{ .Values.promtail.image.tag }}"
          imagePullPolicy: {{ .Values.promtail.image.pullPolicy }}
          args:
            - "-config.file=/etc/promtail/promtail-config.yaml"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.promtail.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "monitoring.fullname" . }}-promtail-config
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
{{- end }}
