{{- if and .Values.enabled .Values.tempo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-tempo
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tempo.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
{{- end }}
