package platform

import (
	"errors"
	"fmt"

	"github.com/sukko-dev/sukko/internal/shared/crypto"
)

// CredentialsConfig holds the shared AES-256 encryption key used by both the
// provisioning service (for push credentials and webhook secrets) and the
// webhook-worker (for decrypting webhook secrets at HMAC computation time).
// Embedded by both ProvisioningConfig and WebhookWorkerConfig.
// Constitution §I: shared fields defined once in a shared struct, never duplicated.
type CredentialsConfig struct {
	CredentialsEncryptionKey string `env:"CREDENTIALS_ENCRYPTION_KEY" redact:"true"` // AES encryption key (hex-encoded, 32 bytes) for encrypting sensitive credentials at rest (push provider keys and webhook signing secrets).
}

// Validate checks that the encryption key is present and decodes to exactly 32 bytes.
// Called by both WebhookWorkerConfig.Validate() and ProvisioningConfig.Validate()
// via embedding — fails fast at startup rather than at first DB write.
func (c *CredentialsConfig) Validate() error {
	if c.CredentialsEncryptionKey == "" {
		return errors.New("CREDENTIALS_ENCRYPTION_KEY is required (32-byte key as hex or base64). Auto-generated by 'sukko init'")
	}
	if _, err := crypto.ParseEncryptionKey(c.CredentialsEncryptionKey); err != nil {
		return fmt.Errorf("CREDENTIALS_ENCRYPTION_KEY: %w", err)
	}
	return nil
}
